config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "home#index"

  get "dashboard", to: "dashboard#index"

  resources :boards do
    resources :lists, except: :show
  end

  namespace :api do
    resources :boards do
      resources :lists, only: :index, controller: "lists"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user

  validates :name, presence: true

  has_many :lists, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  validates :title, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board

  has_many :items, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :boards, dependent: :destroy
end

app/controllers/api/lists_controller.rb
module Api
  class ListsController < ApplicationController
    def index
      @lists = board.lists

      render json: ListSerializer.new(@lists).serializable_hash.to_json
    end

    private

    def board
      @board ||= Board.find(params[:board_id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include Pundit::Authorization
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!
  def new
    @board = Board.new
  end

  def edit
    authorize board
  end

  def show
    authorize board
  end

  def create
    @board = Board.new(board_params.merge(user: current_user))

    if @board.save
      redirect_to root_path, notice: "Board was successfully created."
    else
      render :new
    end
  end

  def update
    authorize board

    if board.update(board_params)
      redirect_to root_path, notice: "Board was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    authorize board

    board.destroy
    redirect_to root_path, notice: "Board was successfully deleted."
  end

  private

  def board_params
    params.require(:board).permit(:name)
  end

  def board
    @board ||= Board.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @boards = Board.order(:created_at)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to dashboard_path if user_signed_in?
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def new
    @list = board.lists.new
  end

  def edit
    @list = board.lists.find(params[:id])
  end

  def create
    @list = board.lists.new(list_params)

    if @list.save
      redirect_to board_path(board), notice: "List was successfully created."
    else
      render :new
    end
  end

  def update
    @list = board.lists.find(params[:id])

    if @list.update(list_params)
      redirect_to board_path(board), notice: "List was successfully updated."
    else
      render :edit
    end
  end

  private

  def board
    @board ||= Board.find(params[:board_id])
  end

  def list_params
    params.require(:list).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/boards/_form.html.erb
<div class="bg-white px-8 py-8 rounded-lg shadow-lg">
  <%= form_with model: board, local: true, class: "space-y8 divide-gray-200" do |f| %>
    <div class="space-y-8 divide divide-gray-200">
      <div>
        <div>
          <% if board.new_record? %>
            <h2 class="text-lg font-semibold text-gray-900">New Board</h2>
            <p class="mt-1 text-sm text-gray-600">This form creates a new board.</p>
          <% else %>
            <h2 class="text-lg font-semibold text-gray-900">Edit Board</h2>
            <p class="mt-1 text-sm text-gray-600">This form updates a board.</p>
          <% end %>
        </div>

        <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
          <div class="sm:col-span-6">
            <%= f.label :name, class: "block text-sm font-medium text-gray-900" %>
            <div class="mt-2">
              <%= f.text_field :name, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6" %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="mt-6 flex items-center justify-end gap-x-6">
      <%= link_to "Cancel", root_path, class: "rounded-md border border-gray-300 bg-white hover:bg-gray-200 text-sm py-2 px-4 font-semibold text-gray-700"%>
      <%= f.submit class: "cursor-pointer rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    </div>
  <% end %>
</div>

app/views/boards/edit.html.erb
<div class="mx-auto max-w-7xl px4 sm:px-6 lg:px-8 py-12">
  <div class="mx-auto max-w-3xl">
    <%= render "form", board: @board %>
  </div>
</div>

app/views/boards/new.html.erb
<div class="mx-auto max-w-7xl px4 sm:px-6 lg:px-8 py-12">
  <div class="mx-auto max-w-3xl">
    <%= render "form", board: @board %>
  </div>
</div>

app/views/boards/show.html.erb
<div class="mx-auto max-w-7xl px-4 py-12">
  <div class="mx-auto max-w-full">
    <p>View board</p>
    <div 
      id="board" 
      data-controller="board" 
      data-api-url= "<%= api_board_lists_path(@board) %>"
      data-board-lists-url= "<%= board_lists_path(@board) %>"
      class="overflow-x-scroll"
    >
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
  <div class="mx-auto max-w-4xl">

    <ul role="list" class="grid grid-clos-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
      <% @boards.each do |board| %>
        <li class="col-span-1 divide-y divide-gray-200 rounded-lg bg-gray-100 shadow-lg">
          <div class="flex w-full items-center justify-between space-x-6 p-6">
            <div class="flex-1 truncate">
              <div class="flex items-center space-x-3">
                <h3 class="text-sm font-medium text-gray-900 truncate hover:text-blue-500"><%= link_to board.name, board_path(board) %></h3>
              </div>
              <p class="mt-1 text-sm text-gray-500 truncate">Created <%= time_ago_in_words(board.created_at) %> ago</p>
            </div>
          </div>
          <div class="-mt-px flex divide-x divide-gray-200">
            <div class="flex w-0 flex-1">
              <%= link_to edit_board_path(board), class: "relative -mr-px inline-flex w-0 flex-1 items-center justify-center rounded-bl-lg border border-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500" do %>
                <span class="ml-3">Edit</span>
              <% end %>
            </div>
            <div class="flex w-0 flex-1">
              <%= link_to board_path(board), data: { "turbo-method": :delete }, class: "relative -mr-px inline-flex w-0 flex-1 items-center justify-center rounded-bl-lg border border-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500" do %>
                <span class="ml-3 text-red-600 hover:text-red-400">Delete</span>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/home/index.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
  <div class="mx-auto max-w-3xl">
    <div>
      <h1 class="font-bold text-4xl">Home#index</h1>
      <p>Find me in app/views/home/index.html.erb</p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="bg-white shadow-lg">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="flex flex-shrink-0 items-center">
        <%= link_to root_path do %>
          <img class="h-8 w-auto" src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
        <% end %>
      </div>
      <% if user_signed_in? %>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <%= link_to "Dashboard", root_path, class: "rounded-md #{ "bg-gray-900 text-white" if controller_name == "dashboard" } hover:bg-gray-700 px-3 py-2 text-sm font-medium text-gay-900 hover:text-white" %>
            <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-900 hover:bg-gray-700 hover:text-white">Team</a>
            <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-900 hover:bg-gray-700 hover:text-white">Projects</a>
            <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-900 hover:bg-gray-700 hover:text-white">Calendar</a>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <% if controller_name == "boards" && action_name == "show" %>
          <%= link_to new_board_list_path(@board), class: "relative mr-3" do %>
            <button class="relative inline-flex items-center p-0.5 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800">
              <span class="inline-flex items-center relative px-3 py-1 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                <svg class="mr-2 w-[18px] h-[18px]" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14m-7 7V5"/>
                </svg>
                New List
              </span>
            </button>
          <% end %>
        <% else %>
          <%= link_to new_board_path, class: "relative mr-3" do %>
            <button class="relative inline-flex items-center p-0.5 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800">
              <span class="inline-flex items-center relative px-3 py-1 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                <svg class="mr-2 w-[18px] h-[18px]" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14m-7 7V5"/>
                </svg>
                New Board
              </span>
            </button>
          <% end %>
        <% end %>
        
        <button type="button" class="relative rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
          <span class="absolute -inset-1.5"></span>
          <span class="sr-only">View notifications</span>
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
          </svg>
        </button>

        <!-- Profile dropdown -->
        <div class="relative ml-3">
          <button type="button" id="dropdownButton" data-dropdown-toggle="dropdown" class="relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
            <img id="avatarButton" class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
          </button>
          
          <!-- Dropdown menu -->
          <div id="dropdown" class="z-10 hidden list-none bg-white divide-y divide-gray-100 rounded-lg shadow w-44">
              <div class="px-4 py-3 text-sm text-gray-900 dark:text-white">
                <div>Bonnie Green</div>
                <div class="font-medium truncate">name@flowbite.com</div>
              </div>
              <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="avatarButton">
                <li>
                  <a href="#" class="block px-4 py-2 hover:bg-gray-100 rounded-md mx-2">Profile</a>
                </li>
                <li>
                  <a href="#" class="block px-4 py-2 hover:bg-gray-100 rounded-md mx-2">Settings</a>
                </li>
                <li>
                  <a href="#" class="block px-4 py-2 hover:bg-gray-100 rounded-md mx-2">Earnings</a>
                </li>
              </ul>
              <div class="py-1">
                <%= link_to "Sing out", destroy_user_session_path, class: "block px-4 py-2 text-sm text-gray-900 hover:bg-red-500 rounded-md mx-2", data: { "turbo-method": :delete } %>
              </div>
          </div>
        </div>
      </div>
    </div>
    <% else %>
      <div class="ml-4 flex flex-shrink-0 items-center" >
        <%= link_to 'Sign in', new_user_session_path, class: "rounded-md px-3 py-2 text-sm font-medium bg-blue-500 tracking-wide text-white hover:bg-blue-800" %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Management Module" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-300" >
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with model: [board, list], local: true, class: "space-y8 divide-gray-200" do |f| %>
  <div class="space-y-8 divide divide-gray-200">
    <div>
      <div>
        <% if @list.new_record? %>
          <h2 class="text-lg font-semibold text-gray-900">New List</h2>
          <p class="mt-1 text-sm text-gray-600">This form creates a new list.</p>
        <% else %>
          <h2 class="text-lg font-semibold text-gray-900">Edit List: <%= list.title %></h2>
          <p class="mt-1 text-sm text-gray-600">This form updates a list.</p>
        <% end %>
      </div>
      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-6">
          <%= f.label :title, class: "block text-sm font-medium text-gray-900" %>
          <div class="mt-2">
            <%= f.text_field :title, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="mt-6 flex items-center justify-end gap-x-6">
    <%= link_to "Cancel", root_path, class: "rounded-md border border-gray-300 bg-white hover:bg-gray-200 text-sm py-2 px-4 font-semibold text-gray-700"%>
    <%= f.submit class: "cursor-pointer rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<div class="mx-auto max-w-7xl px4 sm:px-6 lg:px-8 py-12">
  <div class="mx-auto max-w-3xl">
    <div class="bg-white px-8 py-8 rounded-lg shadow-lg">
      <%= render "form", board: @board, list: @list%>
    </div>
  </div>
</div>